version: '3.8'

services:
  ids:
    build:
      context: ./ids
    container_name: ids_engine
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./logs:/app/logs
    env_file:
      - ./ids/.env
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: ids_backend
    ports:
      - "8000:8000"
    environment:
      LOG_FILE_PATH: /app/logs/alerts.json
      BLOCKED_IPS_PATH: /app/logs/blocked_ips.json
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - ids

  dashboard:
    build:
      context: ./dashboard
    container_name: ids_dashboard
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
