name: Deploy NIDS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop old containers
        run: docker-compose down || true

      - name: Create .env file from Secrets
        run: echo "${{ secrets.IDS_ENV_FILE }}" > ./ids/.env

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Verify deployment
        run: docker ps